/* =====================================================================
   FIRM DATA: edit this array to update the table. The logic below never
   needs to change when you add a firm or fix a value.

   Conventions
   - null                 = not stated / not collected yet (scored as neutral 50, shown as "Data pending")
   - consistencyFunded 0  = no consistency rule on the funded account
   - daysToFirstPayout 0  = daily / on demand
   - minWinDayProfit 0    = no winning-day rule
   - firstPayoutCap "none"= no per-request cap
   - Per-size values use { 25: …, 50: …, 100: …, 150: … } (account size in K); a plain number applies to every size
   - maxFundedAccounts may be a number or a per-size object (firms capped by total $ allocation)
   - restrictedCountries are ISO 3166-1 alpha-2 codes; countryWarnings shows a ⚠️ instead of excluding
   - plans[] holds the firm's other funded plans; each plan only lists what differs from the main plan
   - affiliateUrl / promoCode are for display only: the scoring code never reads them
   Source: futures_prop_firms_funded_payout_rules.xlsx (v2), checked 7–8 Oct 2026.
   ===================================================================== */
export const FIRMS = [
  {
    id: "lucid-trading",
    firm: "Lucid Trading",
    plan: "LucidFlex",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["ATAS", "Bookmap", "Jigsaw Daytradr", "MotiveWave", "MultiCharts", "NinjaTrader", "Quantower", "R Trader Pro", "Sierra Chart", "Tradesea", "TradingView", "Tradovate"],
    restrictedCountries: ["AF", "AL", "AO", "BA", "BB", "BF", "BG", "BI", "BS", "BW", "BY", "BZ", "CD", "CF", "CG", "CI", "CU", "DZ", "EC", "ET", "GH", "GN", "HT", "ID", "IQ", "IR", "IS", "JM", "KE", "KG", "KH", "KP", "KZ", "LA", "LB", "LK", "LR", "LT", "LY", "MA", "ME", "MK", "ML", "MM", "MN", "MU", "MZ", "NA", "NG", "NI", "PA", "PG", "PH", "PK", "RS", "RU", "SC", "SD", "SI", "SN", "SO", "SS", "SY", "TN", "TR", "TT", "TZ", "UA", "UG", "UZ", "VE", "VN", "XK", "YE", "ZA", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Crimea, Kherson, Ukraine regions (Crimea/Donetsk/Luhansk)",
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed on Flex, Pro and Direct. LucidDaily: flat 1 min before to 1 min after red-folder news (hard breach).",
    scalping: "allowed",
    scalpNote: "Allowed; flagged if >50% of profit comes from trades held ≤5 seconds.",
    bots: "allowed",
    botsNote: "Allowed (bots, EAs, API, copy trading on own accounts); HFT prohibited.",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 funded per household (all plans combined).",
    consistencyFunded: 0,
    daysToFirstPayout: 5,
    payoutTime: "5 profitable days",
    minWinDayProfit: { 25: 100, 50: 150, 100: 200, 150: 250 },
    minPayout: 500,
    firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 },
    capNote: "50% of profit up to the cap",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Account cap and bot policy from a third-party summary (PropTradingVibes), not the PFM page.",
    source: "https://propfirmmatch.com/futures/prop-firms/lucid-trading",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "LucidPro", consistencyFunded: 40, daysToFirstPayout: 3, payoutTime: "Every 3 days", minWinDayProfit: 0, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 }, thresholdNote: "Buffer $26,100 / $52,100 / $103,100 / $154,600 + profit goal $250 / $500 / $750 / $1,000" },
      { plan: "LucidDirect (instant)", consistencyFunded: 20, daysToFirstPayout: 5, payoutTime: "Every 5 days", minWinDayProfit: 0, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 }, thresholdNote: "1st profit goal $1,500 / $3,000 / $6,000 / $9,000" },
      { plan: "LucidDaily", news: "banned", newsNote: "Must be flat 1 min before to 1 min after red-folder news (hard breach).", consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "Daily", minWinDayProfit: 0, minPayout: null, firstPayoutCap: "none", capNote: "No per-request cap (daily sim profit cap moves you to live)" }
    ]
  },
  {
    id: "tradeify",
    firm: "Tradeify",
    plan: "Select Flex",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["NinjaTrader", "Quantower", "R Trader", "Sierra Chart", "Tradesea", "TradingView", "Tradovate", "WealthCharts"],
    restrictedCountries: ["AD", "AF", "AL", "AO", "AQ", "AZ", "BA", "BB", "BG", "BI", "BS", "BW", "BY", "CD", "CF", "CI", "CU", "DZ", "EC", "ET", "GH", "ID", "IL", "IQ", "IR", "IS", "JM", "KG", "KH", "KP", "KZ", "LA", "LB", "LK", "LR", "LY", "MA", "ME", "MM", "MN", "MO", "MU", "MY", "NI", "PA", "PG", "PK", "PS", "RU", "SD", "SO", "SS", "SY", "TJ", "TN", "TR", "TT", "UA", "UG", "VE", "VN", "XK", "YE", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Crimea",
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed, no restrictions.",
    scalping: "allowed",
    scalpNote: "Allowed; funded: >50% of trades AND >50% of profit must come from holds >10 s.",
    bots: "conditional",
    botsNote: "Allowed if you prove sole ownership; no HFT; can't run the same bot at other firms.",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 funded per individual / household.",
    consistencyFunded: 0,
    daysToFirstPayout: 5,
    payoutTime: "5 winning days",
    minWinDayProfit: { 25: 100, 50: 150, 100: 200, 150: 250 },
    minPayout: null,
    firstPayoutCap: { 25: 1250, 50: 2500, 100: 3500, 150: 4500 },
    capNote: "50% of profit up to the cap (accounts bought after 1 Sep 2026)",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Select Daily cap label on PFM conflicts (says it applies to accounts bought before 1 Sep 2026).",
    source: "https://propfirmmatch.com/futures/prop-firms/tradeify",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Growth", consistencyFunded: 35, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: { 25: 100, 50: 150, 100: 200, 150: 250 }, minPayout: { 25: 250, 50: 500, 100: 1000, 150: 1500 }, firstPayoutCap: { 25: 1000, 50: 1500, 100: 2000, 150: 2500 } },
      { plan: "Select Daily", consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "Daily", minWinDayProfit: 0, minPayout: 250, firstPayoutCap: { 25: 600, 50: 1250, 100: 1750, 150: 2500 } },
      { plan: "Lightning (instant)", consistencyFunded: 20, daysToFirstPayout: 0, payoutTime: "No day count", minWinDayProfit: 0, minPayout: 1000, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 }, thresholdNote: "Profit goal 6% for the 1st payout" }
    ]
  },
  {
    id: "fundednext-futures",
    firm: "FundedNext Futures",
    plan: "Legacy",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100],
    platforms: ["NinjaTrader", "TradingView", "Tradovate"],
    restrictedCountries: ["AF", "AG", "AL", "AQ", "BD", "BF", "BI", "BV", "BY", "BZ", "CD", "CG", "CI", "CK", "CU", "CV", "DJ", "ER", "FJ", "GD", "GW", "IQ", "IR", "JO", "KM", "KP", "LA", "LB", "LK", "LS", "LY", "ML", "MM", "MW", "MY", "PS", "RU", "RW", "SD", "SL", "SO", "SS", "SY", "TD", "TJ", "TL", "TV", "UA", "VE", "VN", "YE"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: "A second PFM list (~80 countries incl. Morocco, Nigeria, Turkey, Pakistan) can trade sim but is reviewed separately for live.",
    news: "allowed",
    newsNote: "Allowed, no restrictions.",
    scalping: "restricted",
    scalpNote: "Trades <10 s count as micro-scalping: warning at 30% of profit, profit deducted at ≥40% (funded); tick scalping banned.",
    bots: "allowed",
    botsNote: "Allowed incl. EAs; sub-second HFT banned; copying signals banned.",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 active funded per user/household (max 10 issued per month).",
    consistencyFunded: 0,
    daysToFirstPayout: 5,
    payoutTime: "5 benchmark days",
    minWinDayProfit: { 25: 100, 50: 200, 100: 200 },
    minPayout: 250,
    firstPayoutCap: { 25: 3000, 50: 6000, 100: 6000 },
    capNote: "50% of profit (100% after 30 benchmark days), max shown",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "News/bot policy from PipBack; account cap from FundedNext help center.",
    source: "https://propfirmmatch.com/futures/prop-firms/fundednext-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Flex", accountSizes: [50, 100, 150], consistencyFunded: 0, daysToFirstPayout: 5, payoutTime: "5 benchmark days", minWinDayProfit: { 50: 200, 100: 200, 150: 250 }, minPayout: 250, firstPayoutCap: { 50: 1500, 100: 2500, 150: 4000 } },
      { plan: "Rapid Pro", accountSizes: [25, 50, 100], consistencyFunded: 40, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: 250, firstPayoutCap: { 25: 800, 50: 1200, 100: 2500 }, capNote: "Per cycle, max 5 withdrawals" },
      { plan: "Rapid Daily", accountSizes: [25, 50, 100], consistencyFunded: 0, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: 250, firstPayoutCap: { 25: 800, 50: 1200, 100: 2500 }, capNote: "Per cycle, max 5 withdrawals" }
    ]
  },
  {
    id: "my-funded-futures",
    firm: "My Funded Futures",
    plan: "Rapid",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["ATAS", "Deepcharts", "DeepDom", "NinjaTrader", "Quantower", "TradingView", "Tradovate", "Volumetrica Trading"],
    restrictedCountries: ["AE", "AF", "AL", "AO", "BA", "BB", "BF", "BG", "BI", "BS", "BW", "BY", "CD", "CF", "CI", "CM", "CN", "CU", "DZ", "EC", "ET", "GH", "GI", "GY", "HK", "HR", "HT", "ID", "IQ", "IR", "IS", "JM", "JO", "KE", "KH", "KP", "LA", "LB", "LK", "LR", "LY", "MA", "ME", "MK", "ML", "MM", "MN", "MT", "MU", "MY", "MZ", "NA", "NG", "NI", "NR", "PA", "PG", "PH", "PK", "QA", "RO", "RS", "RU", "RW", "SD", "SI", "SN", "SO", "SS", "SY", "TG", "TM", "TN", "TR", "TT", "TW", "TZ", "UA", "UG", "UZ", "VE", "VN", "XK", "YE", "ZA", "ZW"],
    countryWarnings: { FR: "\"France Metropolitan\" is on this firm's restricted list. Confirm with the firm." },
    restrictedRegions: "Crimea",
    countryNote: "List includes \"France Metropolitan\": shown as a warning for France, confirm with the firm.",
    news: "restricted",
    newsNote: "Pro, Rapid, Rapid EOD funded: no positions 2 min before to 2 min after Tier-1 news. Builder unrestricted.",
    scalping: null,
    scalpNote: "Not stated on PFM (HFT not allowed).",
    bots: "allowed",
    botsNote: "Allowed if it doesn't exploit sim fills; HFT banned.",
    maxFundedAccounts: { 25: 5, 50: 5, 100: 3, 150: 3 },
    maxFundedNote: "Up to 5 sim-funded (25K/50K only); 3 if any is 100K/150K.",
    consistencyFunded: 0,
    daysToFirstPayout: 0,
    payoutTime: "Daily (24 h after 1st trade)",
    minWinDayProfit: 0,
    minPayout: 500,
    firstPayoutCap: null,
    capNote: "Not stated",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Account cap from MFFU help center.",
    source: "https://propfirmmatch.com/futures/prop-firms/my-funded-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Builder", accountSizes: [25, 50], news: "allowed", newsNote: "Builder: no news restriction.", consistencyFunded: 50, daysToFirstPayout: 2, payoutTime: "2 trading days", minWinDayProfit: 0, minPayout: { 25: 250, 50: 500 }, firstPayoutCap: { 25: 1000, 50: 2000 } },
      { plan: "Pro", accountSizes: [50, 100, 150], consistencyFunded: 0, daysToFirstPayout: 14, payoutTime: "Every 14 days", minWinDayProfit: 0, minPayout: 1000, firstPayoutCap: "none", capNote: "No per-request cap; $100,000 total sim payouts per user" },
      { plan: "Rapid EOD", accountSizes: [25, 50], consistencyFunded: 0, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: 0, minPayout: 500, firstPayoutCap: null, drawdownType: "EOD" }
    ]
  },
  {
    id: "top-one-futures",
    firm: "Top One Futures",
    plan: "Elite Access",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["BlackArrow Pro", "NinjaTrader", "TradingView", "Tradovate", "WealthCharts"],
    restrictedCountries: ["AF", "AL", "AM", "AO", "AQ", "AZ", "BA", "BB", "BF", "BI", "BS", "BW", "BY", "CD", "CF", "CI", "CU", "DJ", "DZ", "EC", "ET", "GH", "GW", "ID", "IQ", "IR", "IS", "JM", "JO", "KH", "KP", "KW", "KZ", "LA", "LB", "LK", "LR", "LS", "LY", "MA", "ME", "MK", "MM", "MN", "MU", "MW", "NI", "PA", "PG", "PH", "PK", "PS", "RU", "RW", "SD", "SL", "SO", "SS", "SY", "TD", "TJ", "TL", "TN", "TR", "TT", "UA", "UG", "VE", "VN", "XK", "YE", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Crimea",
    countryNote: null,
    news: "restricted",
    newsNote: "Elite funded: no trading 2 min before/after high-impact news. Allowed on Instant, Ignite & evaluations.",
    scalping: "restricted",
    scalpNote: "Every trade must be held >10 s.",
    bots: "banned",
    botsNote: "Not allowed (no bots, scripts or EAs).",
    maxFundedAccounts: { 25: 16, 50: 8, 100: 4, 150: 2 },
    maxFundedNote: "No count limit, but combined balance capped at $400,000 (PFM lists $4.2M, confirm).",
    consistencyFunded: 40,
    daysToFirstPayout: 5,
    payoutTime: "5 profitable days",
    minWinDayProfit: { 25: 200, 50: 250, 100: 300, 150: 350 },
    minPayout: 500,
    firstPayoutCap: { 25: 1000, 50: 1500, 100: 2000, 150: 2500 },
    capNote: "≥50% of each request must be new profit",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "$400K cap from Top One help center; PFM lists max allocation as $4.2M.",
    source: "https://propfirmmatch.com/futures/prop-firms/top-one-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Elite Daily", consistencyFunded: 0, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: 500, firstPayoutCap: { 25: 750, 50: 1000, 100: 1500, 150: 2250 } },
      { plan: "Instant Sim Funded", news: "allowed", newsNote: "Allowed on Instant.", consistencyFunded: 20, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: { 25: 250, 50: 500, 100: 1000, 150: 1500 }, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 } },
      { plan: "Ignite", news: "allowed", newsNote: "Allowed on Ignite.", consistencyFunded: 15, daysToFirstPayout: 0, payoutTime: "No minimum days", minWinDayProfit: null, minPayout: 250, firstPayoutCap: { 25: 500, 50: 1000, 100: 1500, 150: 2000 } }
    ]
  },
  {
    id: "apex-trader-funding",
    firm: "Apex Trader Funding",
    plan: "EOD",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["ATAS", "Bookmap", "Deepcharts", "EdgeProX", "Finamark", "Jigsaw Daytradr", "MotiveWave", "NinjaTrader", "Quantower", "R Trader Pro", "Sierra Chart", "TradingView", "Tradovate", "VolFix", "WealthCharts"],
    restrictedCountries: ["AF", "AZ", "BD", "BF", "BH", "BI", "BJ", "BN", "BY", "CF", "CG", "CI", "CM", "CN", "CU", "CY", "DZ", "EG", "EH", "ER", "GA", "GD", "GN", "GW", "HT", "IQ", "IR", "JE", "JO", "KE", "KP", "KW", "KZ", "LB", "LK", "LR", "LS", "LV", "LY", "MA", "MD", "MG", "MM", "MN", "MR", "MU", "MV", "MZ", "NA", "NC", "NE", "NG", "NI", "NP", "OM", "PG", "PK", "PM", "PS", "QA", "RE", "RS", "RU", "RW", "SA", "SD", "SN", "SO", "SS", "SY", "TD", "TG", "TN", "TR", "TT", "TZ", "UA", "UG", "UZ", "VE", "VN", "VU", "YE", "ZA", "ZM", "ZW"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed as part of a normal strategy (no orders on both sides of a release).",
    scalping: "allowed",
    scalpNote: "Not banned outright; extreme risk/reward (e.g. 5-tick target, 150-tick stop) prohibited.",
    bots: "banned",
    botsNote: "Not allowed (manual only); copy trading OK on the same user ID.",
    maxFundedAccounts: 20,
    maxFundedNote: "Up to 20 Performance Accounts (PropTradingVibes, Aug 2026).",
    consistencyFunded: 50,
    daysToFirstPayout: 5,
    payoutTime: "5 winning days",
    minWinDayProfit: { 25: 100, 50: 250, 100: 300, 150: 350 },
    minPayout: 500,
    firstPayoutCap: { 25: 1000, 50: 1500, 100: 2000, 150: 2500 },
    capNote: "Rising by payout number; max 6 payouts per account",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: "EOD",
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "PFM FAQ mentions a 30% consistency rule without limiting it to Legacy.",
    source: "https://propfirmmatch.com/futures/prop-firms/apex-trader-funding",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Intraday", consistencyFunded: 50, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: { 25: 100, 50: 200, 100: 250, 150: 300 }, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 1500, 100: 2000, 150: 2500 }, drawdownType: "Intraday" },
      { plan: "Legacy", accountSizes: [25, 50, 100, 150, 250, 300], consistencyFunded: 30, daysToFirstPayout: 8, payoutTime: "8 trading days (5 profitable)", minWinDayProfit: 50, minPayout: 500, firstPayoutCap: { 25: 1500, 50: 1500, 100: 1500, 150: 1500 }, capNote: "$1,500 first payout, uncapped from the 6th" }
    ]
  },
  {
    id: "traders-launch",
    firm: "Traders Launch",
    plan: "Standard funded",
    logo: null,
    founded: null,
    accountSizes: [100, 200, 300],
    platforms: ["Quantower", "TradingView", "Volumetrica Trading"],
    restrictedCountries: ["BY", "CU", "IR", "KP", "MM", "RU", "SD", "SS", "SY", "VE", "ZW"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed.",
    scalping: null,
    scalpNote: "Not stated.",
    bots: "conditional",
    botsNote: "Allowed, EAs need pre-approval.",
    maxFundedAccounts: null,
    maxFundedNote: "Not stated (PFM max allocation $1.5M).",
    consistencyFunded: 0,
    daysToFirstPayout: 0,
    payoutTime: "No minimum (crypto daily, ACH 24 h, wire weekly)",
    minWinDayProfit: 0,
    minPayout: 200,
    firstPayoutCap: "none",
    capNote: "No cap (payouts paused at $100K cumulative for scaling review)",
    thresholdNote: "Grow 1% above start, then moved to live",
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: null,
    source: "https://propfirmmatch.com/futures/prop-firms/traders-launch",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "TL Early Access", accountSizes: [25, 50, 100], consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "No minimum", minWinDayProfit: 0, minPayout: 200, firstPayoutCap: "none" },
      { plan: "Legacy NYC", accountSizes: [200, 300], consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "No minimum", minWinDayProfit: 0, minPayout: 200, firstPayoutCap: "none" }
    ]
  },
  {
    id: "funded-futures-family",
    firm: "Funded Futures Family",
    plan: "Prime",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["NinjaTrader", "TradingView", "Tradovate", "WealthCharts"],
    restrictedCountries: ["AF", "AO", "BI", "BY", "CD", "CF", "CI", "CU", "DZ", "ET", "HT", "IQ", "IR", "KP", "LB", "LK", "LY", "MA", "ME", "ML", "MN", "MU", "NI", "PG", "PK", "RU", "SD", "SO", "SS", "SY", "TN", "TR", "TT", "UA", "UG", "VE", "VN", "XK", "YE", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Chinese Military Companies, Darfur, Kherson, Ukraine regions (Crimea/Donetsk/Luhansk), Zaporizhzhia",
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed through all news incl. Tier 1.",
    scalping: "allowed",
    scalpNote: "Allowed; >50% of trades and profit must come from holds >10 s.",
    bots: "banned",
    botsNote: "Not allowed (manual only); copy trading OK.",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 funded per user.",
    consistencyFunded: 40,
    daysToFirstPayout: 3,
    payoutTime: "3 winning days",
    minWinDayProfit: 200,
    minPayout: null,
    firstPayoutCap: { 25: 1000, 50: 2000, 100: 3000, 150: 3500 },
    capNote: "$100K lifetime cap per user",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: null,
    source: "https://propfirmmatch.com/futures/prop-firms/funded-futures-family",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Premier Plus", consistencyFunded: 40, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: 200, minPayout: null, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 }, capNote: "50% of profit up to the cap" },
      { plan: "Straight to Funded (S2F)", consistencyFunded: 25, daysToFirstPayout: 7, payoutTime: "7 winning days", minWinDayProfit: 200, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 } },
      { plan: "Velocity", consistencyFunded: 40, daysToFirstPayout: 3, payoutTime: "3 winning days (daily with add-on)", minWinDayProfit: 200, minPayout: null, firstPayoutCap: { 25: 750, 50: 1250, 100: 2250, 150: 3250 } },
      { plan: "Base", consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "Daily", minWinDayProfit: 200, minPayout: 500, firstPayoutCap: null, capNote: "$500–$1,000 (size split not stated)" }
    ]
  },
  {
    id: "blue-guardian-futures",
    firm: "Blue Guardian Futures",
    plan: "Standard",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["Deepcharts", "NinjaTrader", "TradingView", "Tradovate"],
    restrictedCountries: ["AD", "AF", "AL", "AO", "BA", "BB", "BG", "BI", "BS", "BW", "BY", "CD", "CF", "CI", "CU", "DZ", "EC", "ET", "GH", "ID", "IL", "IQ", "IR", "IS", "JM", "KH", "KP", "LA", "LB", "LK", "LR", "LY", "MA", "ME", "MM", "MN", "MU", "MY", "NI", "PA", "PG", "PK", "RU", "SD", "SO", "SS", "SY", "TN", "TR", "TT", "UA", "UG", "VE", "VN", "XK", "YE", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Crimea",
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed.",
    scalping: "allowed",
    scalpNote: "Allowed; <50% of profit may come from trades held <10 s.",
    bots: "banned",
    botsNote: "Not allowed (bots/AI/automation prohibited).",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 funded traded at once (Propvator).",
    consistencyFunded: 40,
    daysToFirstPayout: null,
    payoutTime: "Not stated",
    minWinDayProfit: null,
    minPayout: null,
    firstPayoutCap: { 25: 1500, 50: 2500, 100: 3000, 150: 4000 },
    capNote: null,
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Min payout not stated (Reserve lists $100 / $150 / $200 / $250, may be min payout or winning-day threshold).",
    source: "https://propfirmmatch.com/futures/prop-firms/blue-guardian-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Reserve", consistencyFunded: 0, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: null, minPayout: null, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 }, capNote: "50% of profit up to the cap" },
      { plan: "Express", consistencyFunded: 0, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: null, firstPayoutCap: { 25: 600, 50: 1100, 100: 1500, 150: 2500 }, capNote: "Daily cap" },
      { plan: "Direct (instant)", consistencyFunded: 20, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: null, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 } }
    ]
  },
  {
    id: "futureselite",
    firm: "FuturesElite",
    plan: "Prime",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["ATAS", "Deepcharts", "Deepmap", "NinjaTrader", "Quantower", "Tradovate", "Volumetrica Trading", "WealthCharts"],
    restrictedCountries: ["AF", "AL", "AO", "BA", "BB", "BF", "BG", "BI", "BS", "BW", "BY", "BZ", "CD", "CF", "CG", "CI", "CU", "DZ", "EC", "ET", "GH", "GN", "HT", "ID", "IQ", "IR", "IS", "JM", "KE", "KG", "KH", "KP", "KR", "KZ", "LA", "LB", "LK", "LR", "LT", "LY", "MA", "ME", "MK", "ML", "MM", "MN", "MU", "MZ", "NA", "NG", "NI", "PA", "PG", "PH", "PK", "RS", "RU", "SC", "SD", "SI", "SN", "SO", "SS", "SY", "TN", "TR", "TT", "TZ", "UA", "UG", "UZ", "VE", "VN", "XK", "YE", "ZA", "ZW"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "restricted",
    newsNote: "Funded: flat 2 min before to 4 min after Tier-1 news (trades voided).",
    scalping: "restricted",
    scalpNote: "Trades <10 s / ≤1 NQ point restricted; funded scalp profit is removed from the buffer.",
    bots: "banned",
    botsNote: "Not allowed (fully automated AI/bots).",
    maxFundedAccounts: null,
    maxFundedNote: "Not stated (PFM max allocation $1.5M).",
    consistencyFunded: 40,
    daysToFirstPayout: null,
    payoutTime: "Not stated",
    minWinDayProfit: null,
    minPayout: { 25: 500, 50: 500, 100: 900, 150: 1100 },
    firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 },
    capNote: null,
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Elite evaluation consistency listed as both 40% and 50% on PFM.",
    source: "https://propfirmmatch.com/futures/prop-firms/futureselite",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Elite", consistencyFunded: 0, daysToFirstPayout: 6, payoutTime: "6 winning days (announcement says 5)", minWinDayProfit: { 25: 100, 50: 150, 100: 250, 150: 350 }, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 }, capNote: "50% of profit up to the cap" },
      { plan: "Nitro", consistencyFunded: 0, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 2800 } },
      { plan: "Instant", accountSizes: [50, 100, 150], consistencyFunded: 20, daysToFirstPayout: 10, payoutTime: "10 profitable days", minWinDayProfit: { 50: 150, 100: 250, 150: 350 }, minPayout: 0, firstPayoutCap: { 50: 1500, 100: 2500, 150: 3500 }, capNote: "50% of profit up to the cap" }
    ]
  },
  {
    id: "e8-futures",
    firm: "E8 Futures",
    plan: "E8 Signature",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["TradingView", "Tradovate"],
    restrictedCountries: ["AE", "AF", "AL", "AO", "AQ", "BA", "BB", "BF", "BG", "BI", "BS", "BW", "BY", "CD", "CF", "CG", "CI", "CM", "CN", "CU", "DJ", "DZ", "ET", "GH", "GI", "GW", "HR", "HT", "ID", "IQ", "IR", "IS", "JM", "JO", "KE", "KH", "KP", "LA", "LB", "LK", "LR", "LS", "LY", "ME", "MK", "ML", "MM", "MN", "MU", "MW", "MZ", "NA", "NG", "NI", "PA", "PG", "PH", "PK", "PS", "QA", "RO", "RS", "RU", "RW", "SD", "SI", "SL", "SN", "SO", "SS", "SY", "TD", "TJ", "TL", "TN", "TR", "TT", "TZ", "UA", "UG", "VE", "VN", "XK", "YE", "ZA", "ZM", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Crimea",
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed, no restrictions.",
    scalping: "restricted",
    scalpNote: "≥50% of profit must come from trades held ≥10 s; tick scalping banned.",
    bots: "banned",
    botsNote: "Not allowed (incl. semi-automated); HFT = 300+ trades/day.",
    maxFundedAccounts: 5,
    maxFundedNote: "5 Signature or 3 Zero performance accounts per household.",
    consistencyFunded: 35,
    daysToFirstPayout: 0,
    payoutTime: "On demand (then 5 profitable days between)",
    minWinDayProfit: { 25: 75, 50: 150, 100: 300, 150: 450 },
    minPayout: 100,
    firstPayoutCap: { 25: 1000, 50: 1250, 100: 2250, 150: 3250 },
    capNote: "Max 5 payouts, then the account closes",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Min payout, frequency, winning days and account cap from TheGodFunded. Winning day = 0.3% realized profit (read here as 0.3% of account size).",
    source: "https://propfirmmatch.com/futures/prop-firms/e8-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "E8 Zero Starter", accountSizes: [50, 100, 200], consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "Daily", minWinDayProfit: null, minPayout: 100, firstPayoutCap: { 50: 1000, 100: 1600 }, capNote: "$2,100 on 200K" },
      { plan: "E8 Zero Max", accountSizes: [50, 100, 200], consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "Daily", minWinDayProfit: null, minPayout: 100, firstPayoutCap: { 50: 3000, 100: 5000 }, capNote: "$7,000 on 200K" }
    ]
  },
  {
    id: "tradeday",
    firm: "TradeDay",
    plan: "QuickPay",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["ATAS", "Bookmap", "EdgeProX", "Finamark", "Jigsaw Daytradr", "MotiveWave", "MultiCharts", "NinjaTrader", "OverCharts", "Quantower", "R Trader Pro", "Sierra Chart", "TradingView", "Tradovate", "VolFix", "WealthCharts"],
    restrictedCountries: ["AF", "AL", "AO", "BA", "BB", "BF", "BG", "BI", "BW", "BY", "CD", "CF", "CI", "CM", "CU", "DZ", "EC", "ET", "GH", "GI", "GU", "GY", "HR", "HT", "ID", "IQ", "IR", "IS", "JM", "JO", "KP", "KY", "LA", "LB", "LK", "LR", "LY", "MA", "MC", "ME", "MK", "ML", "MM", "MN", "MT", "MU", "MZ", "NA", "NG", "NI", "NP", "PA", "PG", "PH", "PK", "PR", "PS", "RO", "RS", "RU", "SD", "SI", "SN", "SO", "SS", "SY", "TN", "TT", "TZ", "UA", "UG", "VE", "VG", "VI", "VN", "XK", "YE", "ZA", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Crimea, Darfur, Magnitsky",
    countryNote: "Germany & Canada (ex-Ontario): sim funded only.",
    news: "banned",
    newsNote: "Not allowed: auto-flattened 2 min before to 2 min after Tier-1 news.",
    scalping: "allowed",
    scalpNote: "Allowed (HFT >200 trades/day banned).",
    bots: "conditional",
    botsNote: "Own EAs allowed; bought third-party bots forbidden.",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 Funded Sim + 5 Funded Live.",
    consistencyFunded: 0,
    daysToFirstPayout: 0,
    payoutTime: "On demand",
    minWinDayProfit: 0,
    minPayout: 250,
    firstPayoutCap: "none",
    capNote: "$10,000 total sim payouts, then reviewed for live",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: 80,
    splitNote: "50/50 while profit < $4,000, 80/20 above",
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "PFM firm-rules section says funded has no consistency rule, which conflicts with FastPass 45%.",
    source: "https://propfirmmatch.com/futures/prop-firms/tradeday",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "FastPass EOD", consistencyFunded: 45, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: { 50: 150, 100: 200, 150: 250 }, minPayout: 250, firstPayoutCap: { 25: 750, 50: 1500, 100: 1875, 150: 2250 }, capNote: "50% of balance up to the cap; 5 payouts total", drawdownType: "EOD" }
    ]
  },
  {
    id: "take-profit-trader",
    firm: "Take Profit Trader",
    plan: "PRO",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 75, 100, 150],
    platforms: ["ATAS", "Bookmap", "Finamark", "Investor/RT", "Jigsaw Daytradr", "MotiveWave", "MultiCharts", "NinjaTrader", "Quantower", "R Trader", "Trade Navigator", "TradingView", "Tradovate", "VolFix"],
    restrictedCountries: ["AF", "AL", "AO", "BA", "BB", "BF", "BG", "BI", "BJ", "BW", "BY", "BZ", "CC", "CD", "CI", "CK", "CM", "CU", "CV", "CX", "DJ", "DM", "DZ", "EH", "ER", "ET", "FJ", "FK", "FM", "GA", "GH", "GM", "GN", "GQ", "GS", "GW", "GY", "HM", "HR", "HT", "IQ", "IR", "JM", "JO", "KE", "KI", "KM", "KP", "KZ", "LA", "LB", "LK", "LR", "LS", "LY", "MA", "MC", "ME", "MK", "ML", "MM", "MN", "MP", "MR", "MS", "MT", "MU", "MW", "MZ", "NA", "NE", "NG", "NI", "NP", "NR", "PA", "PE", "PG", "PH", "PK", "PS", "QA", "RO", "RS", "RU", "RW", "SC", "SD", "SI", "SJ", "SL", "SN", "SO", "SR", "SS", "ST", "SY", "TD", "TG", "TJ", "TL", "TM", "TN", "TR", "TT", "TV", "TZ", "UA", "UG", "VC", "VE", "VN", "XK", "YE", "YT", "ZA", "ZM", "ZW"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "restricted",
    newsNote: "Flat 1 min before to 1 min after FOMC, NFP, CPI (+ crude inventories / bond auctions for those products).",
    scalping: null,
    scalpNote: "Not stated.",
    bots: "banned",
    botsNote: "Not allowed (no EAs); approved copiers on own accounts only.",
    maxFundedAccounts: 3,
    maxFundedNote: "Up to 3 PRO / PRO+ at once.",
    consistencyFunded: 0,
    daysToFirstPayout: 0,
    payoutTime: "On demand from day 1",
    minWinDayProfit: 0,
    minPayout: 0,
    firstPayoutCap: "none",
    capNote: "No cap. Withdrawals ≤$250 carry a $50 fee",
    thresholdNote: "Buffer zone $26,500 / $52,000 / $77,500 / $103,000 / $154,500",
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: 80,
    splitNote: "80% above the buffer zone (50% if the account is ≤60 days old)",
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Account cap from TPT help center.",
    source: "https://propfirmmatch.com/futures/prop-firms/take-profit-trader",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "PRO+", consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "On demand from day 1", minWinDayProfit: 0, minPayout: 0, firstPayoutCap: "none", thresholdNote: "No buffer" }
    ]
  },
  {
    id: "earn2trade",
    firm: "Earn2Trade",
    plan: "Trader Career Path",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100],
    platforms: ["ATAS", "BlackArrow", "Bookmap", "Finamark", "Inside Edge Trader", "Investor/RT", "Jigsaw Daytradr", "MotiveWave", "MultiCharts", "NinjaTrader", "Photon", "QScalp", "QSI-Quick Screen Trading", "Quantower", "R Trader", "R Trader Pro", "Scalp Tool", "Sierra Chart", "Trade Navigator", "TradingView", "Tradovate", "VolFix"],
    restrictedCountries: ["AF", "AL", "AZ", "CF", "CU", "GI", "IQ", "IR", "KE", "KP", "LY", "ML", "MM", "NG", "NR", "PK", "RU", "SD", "SO", "SS", "SY", "TM", "UA", "VE", "YE"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed.",
    scalping: null,
    scalpNote: "Not stated (high-speed abuse prohibited).",
    bots: "banned",
    botsNote: "Not allowed (no EAs, no copy trading).",
    maxFundedAccounts: 3,
    maxFundedNote: "Up to 3 funded (only 1 can be Live), per TheGodFunded.",
    consistencyFunded: 0,
    daysToFirstPayout: 7,
    payoutTime: "Weekly (paid Wednesdays)",
    minWinDayProfit: 0,
    minPayout: 100,
    firstPayoutCap: { 25: 1750, 50: 3000, 100: 6000 },
    capNote: null,
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: 139,
    activationNote: "$139 LiveSim activation, taken from the first withdrawal",
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: 80,
    splitNote: "50% until profit reaches $1,500 / $2,250 / $3,000, then 80%",
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: null,
    source: "https://propfirmmatch.com/futures/prop-firms/earn2trade",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Gauntlet Mini", accountSizes: [50, 100, 150, 200], consistencyFunded: 0, daysToFirstPayout: 7, payoutTime: "Weekly", minWinDayProfit: 0, minPayout: 100, firstPayoutCap: { 50: 5000, 100: 5000, 150: 5000 }, capNote: "$5,000 per LiveSim account", splitNote: "50% until profit reaches $2,250 / $3,000 / $4,000 / $5,000, then 80%" }
    ]
  },
  {
    id: "aquafunded-futures",
    firm: "AquaFunded Futures",
    plan: "Standard",
    logo: null,
    founded: null,
    accountSizes: [50, 100, 150],
    platforms: ["Deepcharts", "Tradovate"],
    restrictedCountries: ["AF", "AL", "AO", "BA", "BB", "BF", "BG", "BI", "BS", "BW", "BY", "CD", "CF", "CI", "CM", "CN", "CU", "DZ", "EC", "ET", "GH", "HK", "HR", "ID", "IQ", "IR", "IS", "JM", "KE", "KH", "KP", "LA", "LB", "LK", "LR", "LY", "ME", "MK", "ML", "MM", "MN", "MU", "MZ", "NA", "NI", "PA", "PG", "PH", "PK", "QA", "RO", "RS", "RU", "SD", "SI", "SN", "SO", "SS", "SY", "TN", "TR", "TT", "TZ", "UA", "UG", "VE", "VN", "XK", "YE", "ZA", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Crimea",
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed.",
    scalping: "allowed",
    scalpNote: "Allowed; ≥50% of trades and profit from holds >10 s; average RR >0.3.",
    bots: "conditional",
    botsNote: "Fully automated not allowed; semi-automated OK if the trader is present; 100+ trades/day banned.",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 active funded (AquaFutures help center; TheGodFunded says 3).",
    consistencyFunded: 40,
    daysToFirstPayout: 0,
    payoutTime: "On demand",
    minWinDayProfit: 0,
    minPayout: 500,
    firstPayoutCap: { 50: 2000, 100: 2500, 150: 3500 },
    capNote: null,
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: null,
    source: "https://propfirmmatch.com/futures/prop-firms/aquafunded-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Instant", accountSizes: [25, 50, 100, 150], consistencyFunded: 20, daysToFirstPayout: 0, payoutTime: "On demand", minWinDayProfit: 0, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 }, capNote: "Approximate" },
      { plan: "Flex", accountSizes: [50, 100, 150], consistencyFunded: 0, daysToFirstPayout: 5, payoutTime: "5 winning days (6 without DLL)", minWinDayProfit: { 50: 200, 100: 250, 150: 300 }, minPayout: 500, firstPayoutCap: { 50: 2000, 100: 2500, 150: 3000 }, capNote: "50% of profit up to the cap" },
      { plan: "Daily", accountSizes: [50, 100, 150], consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "Daily", minWinDayProfit: 0, minPayout: 500, firstPayoutCap: { 50: 1100, 100: 2200, 150: 3300 } }
    ]
  },
  {
    id: "the-trading-pit-futures",
    firm: "The Trading Pit Futures",
    plan: "Futures Prime",
    logo: null,
    founded: null,
    accountSizes: [50, 100, 150],
    platforms: ["ATAS", "Jigsaw Daytradr", "MotiveWave", "NinjaTrader", "Quantower", "R Trader", "R Trader Pro", "Sierra Chart", "TradingView", "Tradovate", "VolFix", "Volsys"],
    restrictedCountries: ["AF", "AL", "AQ", "BF", "BI", "BY", "CG", "CI", "CU", "DJ", "GW", "IQ", "IR", "KP", "LA", "LS", "LY", "MW", "PS", "RU", "RW", "SD", "SL", "SO", "SS", "TD", "TJ", "TL", "YE"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed.",
    scalping: "allowed",
    scalpNote: "Scalping allowed; micro-scalping (≈10–15 s trades) prohibited.",
    bots: "allowed",
    botsNote: "Allowed (EAs that don't run prohibited strategies).",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 Earning (funded) accounts.",
    consistencyFunded: 0,
    daysToFirstPayout: 5,
    payoutTime: "5 profitable days (requests every 7 days)",
    minWinDayProfit: 150,
    minPayout: 100,
    firstPayoutCap: { 50: 2500, 100: 3500, 150: 5000 },
    capNote: "50% of profit up to the cap",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Min payout, frequency and account cap from TheGodFunded.",
    source: "https://propfirmmatch.com/futures/prop-firms/the-trading-pit-futures",
    lastChecked: "2026-10-08",
    plans: []
  },
  {
    id: "ylos-trading",
    firm: "Ylos Trading",
    plan: "Standard",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150, 300],
    platforms: ["BlackArrow Pro"],
    restrictedCountries: ["AF", "AL", "AM", "AZ", "IR", "KW", "KZ", "LT", "MK", "MY", "PK", "RO", "RU", "TR", "VN"],
    countryWarnings: { RS: "\"Yugoslavia\" is on this firm's restricted list. Confirm with the firm.", ME: "\"Yugoslavia\" is on this firm's restricted list. Confirm with the firm.", XK: "\"Yugoslavia\" is on this firm's restricted list. Confirm with the firm." },
    restrictedRegions: null,
    countryNote: "List includes \"Yugoslavia\": shown as a warning for Serbia, Montenegro and Kosovo.",
    news: "banned",
    newsNote: "Not allowed on funded: must be flat at the release.",
    scalping: "restricted",
    scalpNote: "Most trades held ≤30 s prohibited.",
    bots: "banned",
    botsNote: "Not allowed (only the Order Replicator).",
    maxFundedAccounts: null,
    maxFundedNote: "Not stated (PFM max allocation $6M).",
    consistencyFunded: 40,
    daysToFirstPayout: 7,
    payoutTime: "7 winning days",
    minWinDayProfit: 50,
    minPayout: 500,
    firstPayoutCap: { 25: 1500, 50: 2000, 100: 2500, 150: 2750 },
    capNote: "Until the 4th payout, then moved to live",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: null,
    source: "https://propfirmmatch.com/futures/prop-firms/ylos-trading",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "No Activation", consistencyFunded: 40, daysToFirstPayout: 7, payoutTime: "7 winning days", minWinDayProfit: 50, minPayout: 500, firstPayoutCap: { 25: 1500, 50: 2000, 100: 2500, 150: 2750 } },
      { plan: "Instant Funding", consistencyFunded: 30, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: 200, minPayout: 500, firstPayoutCap: { 25: 1500, 50: 2000, 100: 2500, 150: 2750 } },
      { plan: "Freedom 2.0", consistencyFunded: null, daysToFirstPayout: 0, payoutTime: "Daily", minWinDayProfit: null, minPayout: 250, firstPayoutCap: null, capNote: "$1,000 / $1,500 (sizes not stated)" }
    ]
  },
  {
    id: "daytraders",
    firm: "DayTraders",
    plan: "Pro",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150, 300],
    platforms: ["ATAS", "Bookmap", "Finamark", "Jigsaw Daytradr", "MotiveWave", "Quantower", "R Trader Pro", "Sierra Chart", "VolFix"],
    restrictedCountries: ["AF", "AZ", "BD", "BF", "BH", "BJ", "BN", "BY", "CF", "CG", "CI", "CM", "CN", "CU", "CW", "CY", "DZ", "EG", "EH", "GA", "GD", "HT", "ID", "IQ", "IR", "JE", "JO", "KE", "KW", "KZ", "LB", "LK", "LS", "LY", "MA", "MD", "MG", "MN", "MR", "MU", "MV", "MZ", "NA", "NE", "NG", "NI", "NP", "OM", "PK", "PM", "PS", "QA", "RE", "RS", "RU", "RW", "SA", "SD", "SN", "SO", "SY", "TD", "TG", "TH", "TN", "TR", "TT", "TZ", "UA", "UG", "UZ", "VE", "VN", "XK", "YE", "ZA", "ZM", "ZW"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed (not recommended).",
    scalping: "allowed",
    scalpNote: "Allowed (HFT banned).",
    bots: "allowed",
    botsNote: "Allowed (standard algos; HFT banned).",
    maxFundedAccounts: 5,
    maxFundedNote: "5 funded (up to 2 Pro + 3 S2F).",
    consistencyFunded: 30,
    daysToFirstPayout: 8,
    payoutTime: "8 days between requests",
    minWinDayProfit: { 25: 100, 50: 200, 100: 300, 150: 300 },
    minPayout: 500,
    firstPayoutCap: { 25: 1000, 50: 2000, 100: 3000, 150: 3500 },
    capNote: null,
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "News, scalping, bots and account cap from TradersPost review.",
    source: "https://propfirmmatch.com/futures/prop-firms/daytraders",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Straight-to-Funded (S2F)", accountSizes: [25, 50, 150], consistencyFunded: 20, daysToFirstPayout: 10, payoutTime: "10 days", minWinDayProfit: { 25: 100, 50: 200, 150: 300 }, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 150: 3000 } },
      { plan: "Straight-to-Live (S2L)", consistencyFunded: 0, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: null, firstPayoutCap: null, thresholdNote: "$1,000 above start" }
    ]
  },
  {
    id: "goat-funded",
    firm: "Goat Funded Futures",
    plan: "EOD",
    logo: null,
    founded: null,
    accountSizes: [50, 100, 150],
    platforms: ["ATAS", "Deepcharts", "Deepmap", "NinjaTrader", "Quantower", "Tickblaze", "TradingView", "Tradovate", "Volumetrica Trading"],
    restrictedCountries: ["AF", "AL", "AQ", "BA", "BD", "BF", "BG", "BY", "CF", "CG", "CI", "CL", "CU", "DJ", "DZ", "ET", "GW", "HK", "ID", "IL", "IR", "JO", "JP", "KP", "KR", "LA", "LB", "LK", "LS", "LY", "MA", "ML", "MM", "MW", "MY", "PA", "PH", "PK", "PS", "RO", "RU", "RW", "SD", "SG", "SI", "SL", "SN", "SO", "SS", "SY", "TD", "TG", "TH", "TJ", "TL", "TR", "UG", "VE", "VN", "YE", "ZW"],
    countryWarnings: {},
    restrictedRegions: "ISIL",
    countryNote: null,
    news: "restricted",
    newsNote: "Funded: no orders 2 min before/after high-impact news (profit deducted).",
    scalping: "restricted",
    scalpNote: "Profit from trades <2 min deducted; Flex/Daily need ≥50% of profit from trades >1 min.",
    bots: "allowed",
    botsNote: "Allowed on EOD, 1-Day Pass, Flex, Instant Classic; not on Instant Lite & Goat Daily.",
    maxFundedAccounts: 5,
    maxFundedNote: "5 funded each for EOD / Sprint / Flex; 3 for Instant Classic.",
    consistencyFunded: 30,
    daysToFirstPayout: 7,
    payoutTime: "7 winning days",
    minWinDayProfit: { 25: 50, 50: 100, 100: 200, 150: 300 },
    minPayout: 500,
    firstPayoutCap: { 50: 1500, 100: 2000, 150: 2500 },
    capNote: "Requests only on the 5th–8th / 20th–23rd of the month",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: "EOD",
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Processing fee listed as both 2% and 3%. Account cap from Propvator.",
    source: "https://propfirmmatch.com/futures/prop-firms/goat-funded-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "1-Day Pass", accountSizes: [25, 50, 100], consistencyFunded: 35, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: { 25: 50, 50: 100, 100: 200, 150: 300 }, minPayout: 500, firstPayoutCap: { 25: 800, 50: 1500, 100: 2500 }, capNote: "50% of profit stays as buffer", drawdownType: null },
      { plan: "Flex", accountSizes: [50, 100, 150], consistencyFunded: 0, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: { 25: 50, 50: 100, 100: 200, 150: 300 }, minPayout: 500, firstPayoutCap: { 50: 2000, 100: 2500, 150: 3000 }, capNote: "50% of profit up to the cap", drawdownType: null },
      { plan: "Instant Classic", accountSizes: [25, 50, 75, 100, 150], consistencyFunded: 20, daysToFirstPayout: 10, payoutTime: "7 winning days + 10 calendar days", minWinDayProfit: { 25: 50, 50: 100, 100: 200, 150: 300 }, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 100: 3000, 150: 4000 }, capNote: "$3,000 on 75K", drawdownType: null },
      { plan: "Instant Lite", bots: "banned", botsNote: "Not allowed on Instant Lite.", consistencyFunded: 15, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: { 25: 50, 50: 100, 100: 200, 150: 300 }, minPayout: 500, firstPayoutCap: null, capNote: "$1,000 / $2,000 / $3,000 (sizes not stated)", drawdownType: null },
      { plan: "Goat Daily", accountSizes: [25, 50, 100, 150], bots: "banned", botsNote: "Not allowed on Goat Daily.", consistencyFunded: 0, daysToFirstPayout: 0, payoutTime: "Every 24 h", minWinDayProfit: { 25: 50, 50: 100, 100: 200, 150: 300 }, minPayout: 500, firstPayoutCap: { 25: 650, 50: 1000, 100: 1500, 150: 2500 }, drawdownType: null }
    ]
  },
  {
    id: "the5ers-futures",
    firm: "The5ers Futures",
    plan: "Day Trade",
    logo: null,
    founded: null,
    accountSizes: [25, 50],
    platforms: ["BlackArrow"],
    restrictedCountries: ["AF", "BA", "BI", "BY", "CD", "CF", "CG", "CU", "ER", "GN", "GW", "IL", "IQ", "IR", "KP", "LA", "LB", "LR", "LY", "MM", "PG", "PS", "RU", "SD", "SO", "SS", "SY", "VE", "VU", "YE"],
    countryWarnings: {},
    restrictedRegions: "Crimea, Kherson, Zaporizhzhia (also Donetsk & Luhansk regions)",
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed, no restrictions.",
    scalping: null,
    scalpNote: "Not stated (HFT / holds of a few seconds banned).",
    bots: "banned",
    botsNote: "Not allowed (algo trading banned).",
    maxFundedAccounts: null,
    maxFundedNote: "Limited, not clearly stated on PFM.",
    consistencyFunded: 40,
    daysToFirstPayout: 14,
    payoutTime: "Every 14 days",
    minWinDayProfit: 0,
    minPayout: 150,
    firstPayoutCap: { 25: 1250, 50: 1500 },
    capNote: "25K: $1,250 total across all payouts; 50K: 3% of balance per payout",
    thresholdNote: "≥4% profit over initial balance",
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Consistency is 40% per position. PFM also says \"no specific minimum profit threshold\", which conflicts with the 4% rule.",
    source: "https://propfirmmatch.com/futures/prop-firms/the5ers-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Swing", consistencyFunded: 40, daysToFirstPayout: 14, payoutTime: "Every 14 days", minWinDayProfit: 0, minPayout: 150, firstPayoutCap: { 25: 1250, 50: 1500 } }
    ]
  },
  {
    id: "blueberry-futures",
    firm: "Blueberry Futures",
    plan: "Ascent",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["BlackArrow"],
    restrictedCountries: ["AU", "BY", "CU", "IR", "KP", "MM", "PK", "RU", "SO", "SY", "VE", "ZW"],
    countryWarnings: {},
    restrictedRegions: "Crimea, Kherson, Ukraine regions (Crimea/Donetsk/Luhansk), Zaporizhzhia",
    countryNote: null,
    news: "restricted",
    newsNote: "No new orders 3 min before/after red-folder news.",
    scalping: "allowed",
    scalpNote: "Manual scalping allowed; tick / sub-second (0–5 s) trading banned.",
    bots: "conditional",
    botsNote: "Allowed only if proprietary and pre-approved.",
    maxFundedAccounts: { 25: 18, 50: 9, 100: 4, 150: 3 },
    maxFundedNote: "Total allocation capped at $450,000 (ThePropFirmGuide).",
    consistencyFunded: 35,
    daysToFirstPayout: 5,
    payoutTime: "5 profitable days",
    minWinDayProfit: 200,
    minPayout: { 25: 250, 50: 500, 100: 750, 150: 1000 },
    firstPayoutCap: { 25: 1500, 50: 2500, 100: 3500, 150: 4500 },
    capNote: null,
    thresholdNote: "Buffer $1,100 / $2,100 / $3,100 / $4,600",
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: null,
    source: "https://propfirmmatch.com/futures/prop-firms/blueberry-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Accelerated", consistencyFunded: 20, daysToFirstPayout: 5, payoutTime: "5 profitable days", minWinDayProfit: 200, minPayout: { 25: 250, 50: 500, 100: 750, 150: 1000 }, firstPayoutCap: { 25: 1500, 50: 2500, 100: 3500, 150: 4500 } }
    ]
  },
  {
    id: "finotive-futures",
    firm: "Finotive Futures",
    plan: "One Step",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["ATAS", "Deepcharts", "NinjaTrader", "Quantower", "TradingView", "Tradovate"],
    restrictedCountries: ["BY", "CU", "IQ", "IR", "KP", "RU", "SY", "UA"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "restricted",
    newsNote: "Funded & Instant: no trades 2 min before/after high-impact news.",
    scalping: "allowed",
    scalpNote: "Allowed; ≤50% of profit from trades held <30 s.",
    bots: "allowed",
    botsNote: "Allowed (must match your style; no latency exploits).",
    maxFundedAccounts: { 25: 40, 50: 20, 100: 10, 150: 6 },
    maxFundedNote: "Total funded allocation capped at $1,000,000 (TheGodFunded).",
    consistencyFunded: 40,
    daysToFirstPayout: 3,
    payoutTime: "3 winning days",
    minWinDayProfit: { 25: 62, 50: 125, 100: 250, 150: 375 },
    minPayout: 500,
    firstPayoutCap: { 25: 1000, 50: 2000, 100: 2500, 150: 3000 },
    capNote: null,
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: null,
    source: "https://propfirmmatch.com/futures/prop-firms/finotive-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Instant", consistencyFunded: 20, daysToFirstPayout: 5, payoutTime: "5 winning days", minWinDayProfit: { 25: 62, 50: 125, 100: 250, 150: 375 }, minPayout: 500, firstPayoutCap: { 25: 1000, 50: 2000, 100: 3000, 150: 4000 } }
    ]
  },
  {
    id: "hola-prime-futures",
    firm: "Hola Prime Futures",
    plan: "1-Step Prime",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150],
    platforms: ["Dx Futures", "NinjaTrader", "TradingView", "Tradovate", "WealthCharts"],
    restrictedCountries: ["AF", "BI", "BY", "CD", "CF", "CN", "CU", "ER", "GN", "GW", "HT", "IN", "IQ", "IR", "KP", "LA", "LY", "MD", "ML", "MM", "NI", "OM", "PK", "RU", "SO", "SY", "TN", "UA", "VN", "YE", "ZW"],
    countryWarnings: {},
    restrictedRegions: null,
    countryNote: null,
    news: "allowed",
    newsNote: "Allowed, no restrictions.",
    scalping: "restricted",
    scalpNote: "Tick scalping and HFT prohibited.",
    bots: "banned",
    botsNote: "Not allowed (no EAs, bots or AI).",
    maxFundedAccounts: null,
    maxFundedNote: "Not stated.",
    consistencyFunded: 35,
    daysToFirstPayout: 5,
    payoutTime: "5 profitable days (weekly)",
    minWinDayProfit: { 25: 100, 50: 150, 100: 200, 150: 250 },
    minPayout: { 25: 250, 50: 500, 100: 1000, 150: 1500 },
    firstPayoutCap: { 25: 1000, 50: 1500, 100: 2000, 150: 2500 },
    capNote: null,
    thresholdNote: "Trailing drawdown locks at starting balance once profit reaches 4% (25K/50K) or 3% (100K/150K)",
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: 90,
    splitNote: "Payouts labelled weekly at 90% split",
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: null,
    source: "https://propfirmmatch.com/futures/prop-firms/hola-prime-futures",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Direct (instant)", consistencyFunded: 20, daysToFirstPayout: null, payoutTime: "Not stated", minWinDayProfit: null, minPayout: { 25: 250, 50: 500, 100: 1000, 150: 1500 }, firstPayoutCap: { 25: 1000, 50: 1500, 100: 2000, 150: 2500 } }
    ]
  },
  {
    id: "topstep",
    firm: "Topstep",
    plan: "Express Funded (Standard path)",
    logo: null,
    founded: null,
    accountSizes: [50, 100, 150],
    platforms: ["TopstepX"],
    restrictedCountries: ["AF", "AO", "BF", "BI", "BY", "CD", "CI", "CU", "DZ", "HT", "IQ", "IR", "KE", "KP", "LB", "LY", "MA", "ML", "MM", "NG", "NI", "PK", "RU", "SD", "SO", "SS", "SY", "TR", "UA", "VE", "XK", "YE"],
    countryWarnings: {},
    restrictedRegions: "Chinese Military Companies, Crimea (incl. Donetsk, Luhansk, Kherson, Zaporizhzhia)",
    countryNote: null,
    news: "restricted",
    newsNote: "Allowed, except the CPI window (≈5 min before/after) blocks new mini positions.",
    scalping: "allowed",
    scalpNote: "Allowed (scalping algorithms that abuse sim fills prohibited).",
    bots: "allowed",
    botsNote: "Allowed (via TopstepX API).",
    maxFundedAccounts: 5,
    maxFundedNote: "Up to 5 active Express Funded Accounts.",
    consistencyFunded: 0,
    daysToFirstPayout: 5,
    payoutTime: "5 winning days",
    minWinDayProfit: 150,
    minPayout: 125,
    firstPayoutCap: { 50: 2000, 100: 3000, 150: 5000 },
    capNote: "50% of balance up to the cap (doubled with a Daily Loss Limit add-on, limited-time offer)",
    thresholdNote: null,
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: null,
    splitNote: null,
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Checked on Topstep's own help center (payout policy, eligibility FAQ, account limit); news & bot rules from PropFirmMatch.",
    source: "https://help.topstep.com/en/articles/8284233",
    lastChecked: "2026-10-08",
    plans: [
      { plan: "Express Funded (Consistency path)", consistencyFunded: 40, daysToFirstPayout: 3, payoutTime: "3 trading days", minWinDayProfit: 150, minPayout: 125, firstPayoutCap: { 50: 3000, 100: 4000, 150: 6000 }, capNote: "50% of balance up to the cap" },
      { plan: "Live Funded", consistencyFunded: 0, daysToFirstPayout: 5, payoutTime: "5 winning days per cycle (daily after 30)", minWinDayProfit: 150, minPayout: 125, firstPayoutCap: "none", capNote: "50% of balance, no $ cap" }
    ]
  },
  {
    id: "oneup-trader",
    firm: "OneUp Trader",
    plan: "Funded",
    logo: null,
    founded: null,
    accountSizes: [25, 50, 100, 150, 250],
    platforms: ["Rithmic (20+ platforms)", "NinjaTrader", "R Trader", "R Trader Pro", "Sierra Chart", "Bookmap", "Jigsaw", "MotiveWave", "MultiCharts", "Quick Screen Trading", "QScalp", "Scalp Tool", "Trade Navigator", "VolFix", "Photon", "Inside Edge Trader", "Track'n'Trade", "Agena Trader", "Medved Trader"],
    restrictedCountries: ["AF", "BF", "BI", "BY", "CD", "CF", "CU", "IQ", "IR", "KP", "LR", "LY", "MM", "SD", "SO", "SY", "YE", "ZM", "ZW"],
    countryWarnings: { AL: "\"The Balkans\" is on this firm's restricted list. Confirm with the firm.", BA: "\"The Balkans\" is on this firm's restricted list. Confirm with the firm.", XK: "\"The Balkans\" is on this firm's restricted list. Confirm with the firm.", ME: "\"The Balkans\" is on this firm's restricted list. Confirm with the firm.", MK: "\"The Balkans\" is on this firm's restricted list. Confirm with the firm.", RS: "\"The Balkans\" is on this firm's restricted list. Confirm with the firm." },
    restrictedRegions: null,
    countryNote: "Country list says \"mainly\" these, so it may be incomplete. \"The Balkans\" is shown as a warning for Balkan countries.",
    news: "banned",
    newsNote: "Not allowed: flat 1 min before to 1 min after listed releases.",
    scalping: "banned",
    scalpNote: "Not allowed: trades <10 s prohibited (micro/tick scalping, HFT).",
    bots: null,
    botsNote: "Not stated in current rules (a 2021 blog said algo trading not allowed). Get written approval.",
    maxFundedAccounts: 3,
    maxFundedNote: "Up to 3 funded at once (only 1 if Express).",
    consistencyFunded: 0,
    daysToFirstPayout: 0,
    payoutTime: "No winning-day rule (Mon–Fri requests)",
    minWinDayProfit: 0,
    minPayout: 1000,
    firstPayoutCap: "none",
    capNote: "No maximum (crypto: $3,000 per request, 1 per week)",
    thresholdNote: "Trailing drawdown $1,500 / $2,500 / $3,500 / $5,000 / $5,500 must stay in the account",
    price: { 25: null, 50: null, 100: null, 150: null },
    activationFee: null,
    activationNote: null,
    drawdownType: null,
    dailyLossLimit: null,
    profitSplit: 90,
    splitNote: "100% of the first $10,000, then 90%",
    payoutsReported: 0,
    payoutsDenied: 0,
    affiliateUrl: null,
    promoCode: null,
    notes: "Not listed on PropFirmMatch. Min payout and threshold from review sites (TradingFunder, PickMyTrade). Funded traders must also trade ≥50% of the eval weekly average and be above start balance every 15 days in the first 90 days.",
    source: "https://help.oneuptrader.com/article/372-funded-trader-rules",
    lastChecked: "2026-10-08",
    plans: []
  }
];
